### ISSUE TITLE
Generate Common Document

### ISSUE THREAD

**Issue by itsnehasharma** [SarahBrown97/MentalDigitalHealthPlatform#19]
- Groups need to meet and work together to generate a common document 
- Discuss the format of the self-reporting variable 
- Discuss protocol, structure, format, 
- How does communication occur between the roles of the 2 groups? 
- Finalize with a jointly owned document

**Comment by comfort48** [comment]
We, group-3 discussed with group-5 regarding the communication channel, and the structure of data that we would be receiving. Finally concluded that, we consume REST API endpoints exposed by group-5 to get the data and the structure would be of type json.
